```{r kmdeathacfunc, cache=cacheon}
kmfunc <- function(xvar, data, xvarname, yjust = c(0, 0)) {
  fit <- survfit(formula(paste("Surv(sos_outtime_death, sos_death == 'Yes') ~ ", xvar)),
    data = data
  )
  
  smod <- summary(coxph(formula(paste0(
      "Surv(sos_outtime_death, sos_death =='Yes') ~ ",
      xvar, " + strata(par)"
    )),
    data = data
    ))
  
  hr <- paste0(
        dF(smod$conf.int[1, 1], dig = 2),
        " (", dF(smod$conf.int[1, 3], dig = 2),
        "-", dF(smod$conf.int[1, 4], dig = 2), "), ", 
      dF(smod$coef[1, 5], dig = 3, p = TRUE))

  # c(bottom, left, top, right)
  par(mar = c(6, 6, 1, 1) + 0.1)
  # par(mar=c(4, 4, 1, 1) + 0.1)
  plot(fit,
    fun = "event",
    ylab = "Death after Covid-19 (%)",
    xscale = 1,
    yscale = 100,
    col = global_kicols,
    mark.time = FALSE,
    bty = "n",
    # xmax = 365.25,
    xlim = c(-0.2, 90),
    ylim = c(0, 1),
    xlab = "Days",
    axes = F,
    lwd = 3,
    lty = c(1, 2),
    xaxs = "i", yaxs = "i"
  )

  matlines(c(0, 0), c(0, 1-fit$surv[1]), col = global_kicols[1], lty = 1, lwd = 3)
  matlines(c(0, 0), c(0, 1-fit$surv[fit$strata[1] + 1]), col = global_kicols[2], lty = 2, lwd = 3)

  axis(2, seq(0, 1, 0.1), seq(0, 1, 0.1) * 100, las = 2)
  axis(1, seq(0, 90, 10), seq(0, 90, 10))

  m11 <- 1 - summary(fit, 50)$surv
  text(50, m11 + yjust, c(paste0("No ", xvarname), xvarname), pos = 4, cex = 1)

  text(5, 0.8, paste0("HR (95% CI), p-value: ", hr), pos = 4)
  
  mtext("No. at risk", side = 1, line = 3, at = -12, adj = 0, cex = 1)

  mtext("No", side = 1, line = 4, at = -10, adj = 0, cex = 1)
  mtext("Yes", side = 1, line = 5, at = -10, adj = 0, cex = 1)

  nrisk <- summary(fit, seq(0, 90, 10))$n.risk

  axis(1, at = seq(0, 90, 10), labels = nrisk[1:10], line = 3, tick = FALSE, cex.axis = 1)
  axis(1, at = seq(0, 90, 10), labels = nrisk[11:20], line = 4, tick = FALSE, cex.axis = 1)
}
```

```{r kmdeathacsglt2, cache=cacheon, dependson="kmdeathacfunc", fig.cap="1-KM Death sglt2 in the matched cohort"}
kmfunc(
  xvar = "sos_ddr_sglt2i",
  data = match_sglt2i_cov,
  xvarname = "SGLT2i",
  yjust = c(+.06, -.06)
)
```

```{r kmdeathacglp1a, cache=cacheon, dependson="kmdeathacfunc", fig.cap="1-KM Death glp1a in the matched cohort"}
kmfunc(
  xvar = "sos_ddr_glp1a",
  data = match_glp1a_cov,
  xvarname = "GLP-1a",
  yjust = c(.04, -.04)
)
```

```{r kmdeathacdpp4i, cache=cacheon, dependson="kmdeathacfunc", fig.cap="1-KM Death dpp4i in the matched cohort"}
kmfunc(
  xvar = "sos_ddr_dpp4i",
  data = match_dpp4i_cov,
  xvarname = "DPP4i",
  yjust = c(-.04, .04)
)
```
