```{r outaftercovid, cache=cacheon}

survmy <- function(modname,
                   matchdata,
                   modvarsmy) {
  out <- data.frame(matrix(NA, ncol = 8, nrow = 3, 1))
  colnames(out) <- c("Patient group", "Model", rep(c("No", "Yes", "p-value interaction"), 2))

  out[1, 1] <- modname

  ## incidence rate
  out[1, 2] <- "Incidence"

  ## all data
  ev <- pop %>%
    filter(sos_covidconfirmed == "Yes") %>%
    group_by(!!sym(modvarsmy[1])) %>%
    summarise(
      ev = sum(sos_death == "Yes"),
      .groups = "rowwise"
    )


  s <- pop %>%
    filter(sos_covidconfirmed == "Yes") %>%
    group_by(!!sym(modvarsmy[1])) %>%
    summarise(
      s = sum(sos_outtime_death / 365.25),
      .groups = "rowwise"
    )
  r <- pois.exact(x = ev$ev, pt = s$s)

  out[1, 3:4] <- paste0(
    ev$ev, ", ",
    dF(s$s, dig = 0), ", ",
    dF(r$rate, dig = 1), " (",
    dF(r$lower, dig = 1), "-",
    dF(r$upper, dig = 1), ")"
  )

  ## match data
  ev <- matchdata %>%
    group_by(!!sym(modvarsmy[1])) %>%
    summarise(
      ev = sum(sos_death == "Yes"),
      .groups = "rowwise"
    )


  s <- matchdata %>%
    group_by(!!sym(modvarsmy[1])) %>%
    summarise(
      s = sum(sos_outtime_death / 365.25),
      .groups = "rowwise"
    )
  r <- pois.exact(x = ev$ev, pt = s$s)

  out[1, 6:7] <- paste0(
    ev$ev, ", ",
    dF(s$s, dig = 0), ", ",
    dF(r$rate, dig = 1), " (",
    dF(r$lower, dig = 1), "-",
    dF(r$upper, dig = 1), ")"
  )


  # cox regressions
  ## crude
  out[2, 2] <- "Crude HR (95% CI), p"

  mod <- coxph(formula(paste0(
    "Surv(sos_outtime_death, sos_death =='Yes') ~ ",
    modvarsmy[1]
  )),
  data = pop %>% filter(sos_covidconfirmed == "Yes")
  )

  smod <- summary(mod)

  out[2, 3:4] <- c(
    "ref", paste0(
      dF(smod$conf.int[1, 1], dig = 2),
      " (", dF(smod$conf.int[1, 3], dig = 2),
      "-", dF(smod$conf.int[1, 4], dig = 2), "), ",
      dF(smod$coef[1, 5], dig = 3, p = TRUE)
    )
  )

  ## adj covariates
  mod <- coxph(formula(paste0(
    "Surv(sos_outtime_death, sos_death =='Yes') ~ ",
    paste(modvarsmy, collapse = " + ")
  )),
  data = pop %>% filter(sos_covidconfirmed == "Yes")
  )
  smod <- summary(mod)

  out[3, 2] <- "Adjusted HR (95% CI), p"
  out[3, 3:4] <- c(
    "ref", paste0(
      dF(smod$conf.int[1, 1], dig = 2),
      " (", dF(smod$conf.int[1, 3], dig = 2),
      "-", dF(smod$conf.int[1, 4], dig = 2), "), ",
      dF(smod$coef[1, 5], dig = 3, p = TRUE)
    )
  )

  ## adj matching
  mod <- coxph(formula(paste0(
    "Surv(sos_outtime_death, sos_death =='Yes') ~ ",
    modvarsmy[1], " + strata(par)"
  )),
  data = matchdata
  )
  smod <- summary(mod)

  out[3, 6:7] <- c(
    "ref", paste0(
      dF(smod$conf.int[1, 1], dig = 2),
      " (", dF(smod$conf.int[1, 3], dig = 2),
      "-", dF(smod$conf.int[1, 4], dig = 2), "), ",
      dF(smod$coef[1, 5], dig = 3, p = TRUE)
    )
  )

  return(out)
}

survmyint <- function(modname,
                      matchdata,
                      modvarsmy,
                      interactionvar) {
  levs <- levels(pop %>% pull(!!sym(interactionvar)))

  if (length(levs) > 2) stop("> 2 levels in interaction variable")

  out <- data.frame(matrix(NA, ncol = 8, nrow = 6, 1))
  colnames(out) <- c("Patient group", "Model", rep(c("No", "Yes", "p-value interaction"), 2))

  rows <- c(1, 4)

  out[rows, 1] <- paste0(modname, "=", levs)

  ## incidence rate

  out[rows, 2] <- "Incidence"


  ## all data
  ev <- pop %>%
    filter(sos_covidconfirmed == "Yes") %>%
    group_by(!!sym(modvarsmy[1]), !!sym(interactionvar)) %>%
    summarise(
      ev = sum(sos_death == "Yes"),
      .groups = "rowwise"
    )

  s <- pop %>%
    filter(sos_covidconfirmed == "Yes") %>%
    group_by(!!sym(modvarsmy[1]), !!sym(interactionvar)) %>%
    summarise(
      s = sum(sos_outtime_death / 365.25),
      .groups = "rowwise"
    )
  r <- pois.exact(x = ev$ev, pt = s$s)

  out[rows, 3:4] <- paste0(
    ev$ev, ", ",
    dF(s$s, dig = 0), ", ",
    dF(r$rate, dig = 1), " (",
    dF(r$lower, dig = 1), "-",
    dF(r$upper, dig = 1), ")"
  )

  ## match data
  ev <- matchdata %>%
    group_by(!!sym(modvarsmy[1]), !!sym(interactionvar)) %>%
    summarise(
      ev = sum(sos_death == "Yes"),
      .groups = "rowwise"
    )

  s <- matchdata %>%
    group_by(!!sym(modvarsmy[1]), !!sym(interactionvar)) %>%
    summarise(
      s = sum(sos_outtime_death / 365.25),
      .groups = "rowwise"
    )
  r <- pois.exact(x = ev$ev, pt = s$s)

  out[rows, 6:7] <- paste0(
    ev$ev, ", ",
    dF(s$s, dig = 0), ", ",
    dF(r$rate, dig = 1), " (",
    dF(r$lower, dig = 1), "-",
    dF(r$upper, dig = 1), ")"
  )

  for (i in seq_along(levs)) {
    # cox regressions
    ## crude
    out[rows[i] + 1, 2] <- "Crude HR (95% CI), p"

    mod <- coxph(formula(paste0(
      "Surv(sos_outtime_death, sos_death =='Yes') ~ ",
      modvarsmy[1], " * relevel(", interactionvar, ", ref = '", levs[i], "')"
    )),
    data = pop %>% filter(sos_covidconfirmed == "Yes")
    )
    smod <- summary(mod)

    out[rows[i] + 1, 5] <- dF(last(smod$coef[, 5]), dig = 3, p = TRUE)

    out[rows[i] + 1, 3:4] <- c(
      "ref", paste0(
        dF(smod$conf.int[1, 1], dig = 2),
        " (", dF(smod$conf.int[1, 3], dig = 2),
        "-", dF(smod$conf.int[1, 4], dig = 2), "), ",
        dF(smod$coef[1, 5], dig = 3, p = TRUE)
      )
    )

    ## adj covariates
    mod <- coxph(formula(paste0(
      "Surv(sos_outtime_death, sos_death =='Yes') ~ ",
      modvarsmy[1], " * relevel(", interactionvar, ", ref = '", levs[i], "') + ",
      paste(modvarsmy, collapse = " + ")
    )),
    data = pop %>% filter(sos_covidconfirmed == "Yes")
    )
    smod <- summary(mod)

    out[rows[i] + 2, 5] <- dF(last(smod$coef[, 5]), dig = 3, p = TRUE)

    out[rows[i] + 2, 2] <- "Adjusted HR (95% CI), p"
    out[rows[i] + 2, 3:4] <- c(
      "ref", paste0(
        dF(smod$conf.int[1, 1], dig = 2),
        " (", dF(smod$conf.int[1, 3], dig = 2),
        "-", dF(smod$conf.int[1, 4], dig = 2), "), ",
        dF(smod$coef[1, 5], dig = 3, p = TRUE)
      )
    )

    ## adj matching
    mod <- coxph(formula(paste0(
      "Surv(sos_outtime_death, sos_death =='Yes') ~ ",
      modvarsmy[1], " * relevel(", interactionvar, ", ref = '", levs[i], "') + strata(par)"
    )),
    data = matchdata
    )
    smod <- summary(mod)

    out[rows[i] + 2, 8] <- dF(last(smod$coef[, 5]), dig = 3, p = TRUE)

    out[rows[i] + 2, 6:7] <- c(
      "ref", paste0(
        dF(smod$conf.int[1, 1], dig = 2),
        " (", dF(smod$conf.int[1, 3], dig = 2),
        "-", dF(smod$conf.int[1, 4], dig = 2), "), ",
        dF(smod$coef[1, 5], dig = 3, p = TRUE)
      )
    )
  }
  return(out)
}

survmyprint <- function(matchdata2, modvarsmy2, title) {
  out11 <- survmy(
    modname = "All",
    matchdata = matchdata2,
    modvarsmy = modvarsmy2
  )
  out12 <- survmyint(
    modname = "Gender",
    matchdata = matchdata2,
    modvarsmy = modvarsmy2,
    interactionvar = "scb_sex"
  )
  out13 <- survmyint(
    modname = "Age",
    matchdata = matchdata2,
    modvarsmy = modvarsmy2[!modvarsmy2 %in% "ns(scb_age, 4)"],
    interactionvar = "scb_age_cat"
  )
  out14 <- survmyint(
    modname = "HF",
    matchdata = matchdata2,
    modvarsmy = modvarsmy2,
    interactionvar = "sos_com_hf"
  )
  out15 <- survmyint(
    modname = "Hypertension",
    matchdata = matchdata2,
    modvarsmy = modvarsmy2,
    interactionvar = "sos_com_hypertension"
  )
  out16 <- survmyint(
    modname = "Kidney disease",
    matchdata = matchdata2,
    modvarsmy = modvarsmy2,
    interactionvar = "sos_com_renal"
  )
  out17 <- survmyint(
    modname = "IHD",
    matchdata = matchdata2,
    modvarsmy = modvarsmy2,
    interactionvar = "sos_com_ihd"
  )
  out18 <- survmyint(
    modname = "Insulin",
    matchdata = matchdata2,
    modvarsmy = modvarsmy2,
    interactionvar = "sos_ddr_insulin"
  )
  out19 <- survmyint(
    modname = "Metformin",
    matchdata = matchdata2,
    modvarsmy = modvarsmy2,
    interactionvar = "sos_ddr_metformin"
  )
  out20 <- survmyint(
    modname = "Stockholm",
    matchdata = matchdata2,
    modvarsmy = modvarsmy2,
    interactionvar = "scb_region_stockholm"
  )

  outcoxall <- rbind(
    out11, out12, out13,
    out14, out15, out16,
    out17, out18, out19,
    out20
  )

  write.xlsx(outcoxall, paste0("./output/tabs/deathaftercovid_", title, "_", Sys.Date(), ".xlsx"), rowNames = FALSE)

  myHeader <- c(" " = 1, " " = 1, "Overall" = 3, "Matched" = 3)
  names(myHeader) <- c(" ", " ", "Overall", "Matched")

  footnote(
    mykable(outcoxall,
      fontsize = 5,
      caption = paste0("All-cause mortality after confirmed Covid-19 ", title),
      longtable = TRUE
    ) %>%
      landscape() %>%
      add_header_above(myHeader),
    general = c(
      "Incidence = no events, sum py, rate/py (95% CI).",
      "Adjusted = In overall cohort adjusted for and in matched cohort matched on ps derived from variables indicated in baseline table.",
      "P-value for interaction is duplicated (same p for both groups per default)"
    )
  )
}
```

```{r outaftercovidsglt2, cache=cacheon, dependson="outaftercovid"}

survmyprint(
  matchdata2 = match_sglt2i_cov,
  modvarsmy2 = c("sos_ddr_sglt2i", "sos_ddr_glp1a", "sos_ddr_dpp4i", "covidmonth", modvarsns),
  title = "sglt2i"
)
```

```{r outaftercovidglp1a, cache=cacheon, dependson="outaftercovid"}

survmyprint(
  matchdata2 = match_glp1a_cov,
  modvarsmy2 = c("sos_ddr_glp1a", "sos_ddr_sglt2i", "sos_ddr_dpp4i", "covidmonth", modvarsns),
  title = "glp1a"
)
```

```{r outaftercoviddpp4i, cache=cacheon, dependson="outaftercovid"}

survmyprint(
  matchdata2 = match_dpp4i_cov,
  modvarsmy2 = c("sos_ddr_dpp4i", "sos_ddr_glp1a", "sos_ddr_sglt2i", "covidmonth", modvarsns),
  title = "dpp4i"
)
```
